version: "3.7"
services:
  db-app:
    build:
      context: ./db
    expose:
      - 5432
    ports:
      - "5432:5432"
    command: /bin/bash -c 'while [ ! -f /var/lib/postgresql/data/PG_VERSION ]; do sleep 1; done; psql -U postgres -f /docker-entrypoint-initdb.d/initDB.sql && psql -U postgres -f /docker-entrypoint-initdb.d/populateDB.sql && psql -U postgres -f /docker-entrypoint-initdb.d/populateTracksDB.sql'

  web:
    build:
      context: ./web
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - db-app