services:
  db-app:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      POSTGRES_DB: fleet
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./web
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      db-app:
        condition: service_healthy